export const constants = {
  FETCH_MOVIES_REQUEST: "FETCH_MOVIES_REQUEST",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
  SORT_MOVIES: "SORT_MOVIES",
  FILTER_MOVIES: "FILTER_MOVIES",
  FETCH_MOVIE_BY_ID_REQUEST: "FETCH_MOVIE_BY_ID_REQUEST",
  SET_MOVIE_ID: "SET_MOVIE_ID"
};
